version: "3.9"

services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - database

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: ohrim
      POSTGRES_PASSWORD: ohrim
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
